version: "3.4"
services:
  products:
    build:
      context: products/.
    environment:
      DB: mongodb://products_db/app
      KAFKA: kafka:9092
    ports:
      - 4000:4000
    depends_on:
      - products_db
      - kafka
    networks:
      - default
  products_db:
    image: mongo:latest
    networks:
      - default
  seed_products:
    build: ./seed_products
    depends_on:
      - products_db
    networks:
      - default
  catalogs:
    build:
      context: catalogs/.
    environment:
      DB: mongodb://catalogs_db/app
      KAFKA: kafka:9092
    ports:
      - 4001:4000
    depends_on:
      - catalogs_db
      - kafka
    networks:
      - default
  catalogs_db:
    image: mongo:latest
    networks:
      - default
  kafka:
    image: spotify/kafka
    command: >
      bash -c
      "(sleep 15s &&
      /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
      --create
      --zookeeper localhost:2181
      --replication-factor 1
      --partitions 1
      --topic PRODUCTS &) && (supervisord -n)"
    networks:
      - default
networks:
  default:
    driver: bridge
